params = {
    'SOURCE_LANGUAGE_NAME': 'Irish',
    'TARGET_LANGUAGE_NAME': 'English',
    'SOURCE_LANGUAGE_TEXT': 'S:/_UNI/HP/MT/repo/code/gru_attention/data/ga-en/ga.txt',
    'TARGET_LANGUAGE_TEXT': 'S:/_UNI/HP/MT/repo/code/gru_attention/data/ga-en/en.txt',
    'VERSION': "03",
    'DATA_SIZE': 500000,
    'N_EPOCHS': 2,
    'BATCH_SIZE': 64,
    'HIDDEN_UNITS': 128,
    'LEARNING_RATE': 0.001,
    'SOURCE_TIMESTEPS': 20,
    'TARGET_TIMESTEPS': 20,
    'TEST_SPLIT': 0.2,
    'VALIDATION_SPLIT': 0.2,
    'MAX_WORDS_PER_SENTENCE': 20,
    'MIN_WORD_OCCURRENCE': 5,
    'PROJECT_PATH': "S:/_UNI/HP/MT/repo/code/gru_attention/",
}
