params = {
    'SOURCE_LANGUAGE_NAME': 'French',
    'TARGET_LANGUAGE_NAME': 'English',
    'SOURCE_LANGUAGE_TEXT': 'C:/Users/40276245/hp/repo/code/gru_attention/data/fr-en/small_vocab/fr.txt',
    'TARGET_LANGUAGE_TEXT': 'C:/Users/40276245/hp/repo/code/gru_attention/data/fr-en/small_vocab/en.txt',
    'VERSION': "01",
    'DATA_SIZE': 200000,
    'N_EPOCHS': 10,
    'BATCH_SIZE': 64,
    'HIDDEN_UNITS': 128,
    'LEARNING_RATE': 0.001,
    'SOURCE_TIMESTEPS': 20,
    'TARGET_TIMESTEPS': 20,
    'TEST_SPLIT': 0.2,
    'VALIDATION_SPLIT': 0.2,
    'MAX_WORDS_PER_SENTENCE': 20,
    'MIN_WORD_OCCURRENCE': 5,
    'PROJECT_PATH': "C:/Users/40276245/hp/repo/code/gru_attention/",
}
