params = {
    'SOURCE_LANGUAGE_NAME': 'French',
    'TARGET_LANGUAGE_NAME': 'English',
    'SOURCE_LANGUAGE_TEXT': 'C:/Users/40276245/hp/repo/code/gru_attention/data/fr-en/small_vocab/fr.txt',
    'TARGET_LANGUAGE_TEXT': 'C:/Users/40276245/hp/repo/code/gru_attention/data/fr-en/small_vocab/en.txt',
    'VERSION': "101",
    'DESCRIPTION': "Testing the small french vocabulary dataset using my new vocabulary limit",
    'DATA_SIZE': 50000,
    'N_EPOCHS': 2,
    'BATCH_SIZE': 64,
    'HIDDEN_UNITS': 128,
    'LEARNING_RATE': 0.001,
    'SOURCE_TIMESTEPS': 20,
    'TARGET_TIMESTEPS': 20,
    'TEST_SPLIT': 0.2,
    'VALIDATION_SPLIT': 0.2,
    'MAX_WORDS_PER_SENTENCE': 20,
    'MIN_WORD_OCCURRENCE': 1,
    'PROJECT_PATH': "C:/Users/40276245/hp/repo/code/gru_attention/",
    'DATA_CLEANED': True,
    'TYPE': 'TRIVIAL-CHILD',
    'FORCE_SOURCE_VOCAB_SIZE': 200,
    'FORCE_TARGET_VOCAB_SIZE': 200,
}
