
params = {
    'VERSION' : "01",
    'DATA_SIZE' : 100000,
    'N_EPOCHS' : 50,
    'BATCH_SIZE' : 64,
    'HIDDEN_UNITS' : 128,
    'LEARNING_RATE' : 0.001,
    'SOURCE_TIMESTEPS' : 20,
    'TARGET_TIMESTEPS' : 20,
    'TEST_SPLIT' : 0.2,
    'VALIDATION_SPLIT' : 0.2,
    'MAX_WORDS_PER_SENTENCE' : 20,
    'MIN_WORD_OCCURRENCE' : 1,
}
